source files
pillarContent
	<gtExample>
	<label: 'Pillar content with Epicea link'>
	^ '! This is an example of build-in Epicea change

First, define a class with one instance variable:

[[[epicea=ombu/step-one.ombu]]]

Second, define accessors to the instance variable:

[[[epicea=ombu/step-two.ombu]]]

Third, you can create a new change file by writting its definition and pressing the create button:

[[[epicea=ombu/step-three.ombu]]]
'
